####################################
#              通用环境            #
####################################
# 数据源配置
spring:
  # 环境配置
  profiles:
    active: dev

  #控制台输出设置
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 1800000
      pool-name: cjHikariPool

  mvc:
    favicon:
      ##关闭默认图标
      enabled: true


#  # jackson
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Shanghai

#  # ldap配置
#  ldap:
#    urls: ldap://172.15.254.121:389
#    base: OU=OU-NanShan,DC=nanshan,DC=com,DC=cn
#    username: CN=ldap2,OU=OU-ServiceAccount,DC=nanshan,DC=com,DC=cn
#    password: 1qaz@WSX
#

#
#  # 邮箱配置
#  mail:
##    protocol: smtp #发送邮件协议, 默认smtp
#    host: mail.nanshan.com.cn #发送邮件服务器
#    port: 25 #端口号
##    default-encoding: utf-8 # 默认utf-8
##    properties.mail.smtp.auth: true
##    username: xieguangming@nanshan.com.cn #QQ邮箱
##    password: xxxxxxxxxxx #客户端授权码
#    properties.mail.smtp.starttls.required: false
#    properties.mail.smtp.ssl.enable: false
#    properties.mail.smtp.starttls.enable: false
#    from: administrator@device.nanshan.com.cn
#
## 监控配置(http://localhost:8000/actuator/health)
#management:
#  server:
#    port: 8000



## shiro配置
#shiro:
#  #登录请求页面
#  loginUrl: /login
#  #登录成功跳转页面
#  successUrl: /index
#  #无权访问资源时的跳转页面
#  unauthorizedUrl: /unAuth
#  #密码加密算法
#  encryptType: MD5
#  #密码加密次数
#  hashTimes: 10
#  initPassword: abCD1234
#  #全局session过期时间30分钟
#  globalSessionTimeout: 60
#  #每隔10分钟检查一次，是否有过期session
#  schedulerInterval: 30
